# Generated by Django 5.1.4 on 2026-06-06 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='must_change_password',
            field=models.BooleanField(default=False, help_text='Если включено, пользователь будет обязан сменить пароль при следующем входе.', verbose_name='Требуется смена пароля'),
        ),
    ]
