# Generated by Django 5.1.4 on 2026-06-06 20:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Название')),
                ('procedures_count', models.PositiveIntegerField(verbose_name='Количество процедур')),
                ('validity_days', models.PositiveIntegerField(verbose_name='Срок действия (дней)')),
                ('discount_percent', models.PositiveIntegerField(default=0, verbose_name='Скидка, %')),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Итоговая цена, руб.')),
            ],
            options={
                'verbose_name': 'Тип абонемента',
                'verbose_name_plural': 'Типы абонементов',
                'ordering': ['total_price'],
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchase_date', models.DateField(auto_now_add=True, verbose_name='Дата покупки')),
                ('procedures_left', models.PositiveIntegerField(verbose_name='Осталось процедур')),
                ('payment_status', models.CharField(choices=[('pending', 'Ожидает оплаты'), ('paid', 'Оплачен'), ('expired', 'Истёк')], default='pending', max_length=20, verbose_name='Статус оплаты')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to=settings.AUTH_USER_MODEL, verbose_name='Клиент')),
                ('subscription_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subscriptions', to='subscriptions.subscriptiontype', verbose_name='Тип абонемента')),
            ],
            options={
                'verbose_name': 'Абонемент',
                'verbose_name_plural': 'Абонементы',
                'ordering': ['-purchase_date'],
            },
        ),
        migrations.CreateModel(
            name='SubscriptionTypeService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.service', verbose_name='Услуга')),
                ('subscription_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subscriptions.subscriptiontype', verbose_name='Тип абонемента')),
            ],
            options={
                'verbose_name': 'Услуга в абонементе',
                'verbose_name_plural': 'Услуги в абонементах',
                'unique_together': {('subscription_type', 'service')},
            },
        ),
        migrations.AddField(
            model_name='subscriptiontype',
            name='services',
            field=models.ManyToManyField(related_name='subscription_types', through='subscriptions.SubscriptionTypeService', to='catalog.service', verbose_name='Доступные услуги'),
        ),
    ]
